/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package IGU.Reparaciones;
import Logica.Reparaciones.Tecnico;
import Logica.Controladora;
import Logica.Reparaciones.Reparacion;
import Logica.Servicios.Sala;
import Logica.Servicios.Servicio;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import java.util.Date;
/**
 *
 * @author Usuario
 */
public class NuevaReparacion extends javax.swing.JFrame {

    Controladora controlLogica = new Controladora();
    
    ArrayList <Tecnico> listaTecnicos = controlLogica.buscarListaTecnico();
    ArrayList <Servicio> listaServicios = controlLogica.buscarListaServicios();
    ArrayList <Sala> listaSalas = controlLogica.buscarListaSala();
    int idServicioSelect;

    public NuevaReparacion() {
        initComponents();
                
        rellenarCampos();
        this.setTitle("Gestion de insumos informaticos");   
    }
    
    private void rellenarCampos() {
        
        Collections.sort(listaServicios, new Comparator <Servicio>() {
            @Override
            public int compare(Servicio o1, Servicio o2) {
                return o1.getNombreServicio().compareTo(o2.getNombreServicio());
            }

        });
        
        //Rellenar campos de servicio
        jCBServicio.removeAllItems();
        
        if(!listaServicios.isEmpty()){         
            jCBServicio.addItem("Seleccione un servicio");
            
            for(Servicio servi : listaServicios){
                jCBServicio.addItem(servi.getNombreServicio());                 
            }
        }
        
        else{
            jCBServicio.addItem("Cargue un servicio");
        }
        
        //Rellenar campos de tecnicos
        jCbReceptor.removeAllItems();
        if(listaTecnicos.isEmpty()){
            jCbReceptor.addItem("Ningun tecnico esta cargado");
        }
        else{
            for(Tecnico tecni : listaTecnicos){
                jCbReceptor.addItem(tecni.getNombre());
            }
        }
        
        //Setear Fechas
        //Fecha de recepcion
        jDateFechaRecepcion.setText(controlLogica.getDate());
        
        //Fecha estimativa (Recepcion + 15 dias)
        Date dt = new Date();
        DateFormat dateFormat = new SimpleDateFormat("dd-M-yyyy hh:mm:ss");
        Date tomorrow = new Date(dt.getTime() + (15000 * 60 * 60 * 24));
        String fecha = dateFormat.format(tomorrow);

        jDateFechaEstimativa.setText(fecha);
    }
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDatePickerUtil1 = new org.jdatepicker.util.JDatePickerUtil();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButtonBack = new javax.swing.JButton();
        jButtonCarga = new javax.swing.JButton();
        jCBServicio = new javax.swing.JComboBox<>();
        jCBTipoRep = new javax.swing.JComboBox<>();
        jCBSala = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextModelo = new javax.swing.JTextPane();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jCbReceptor = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jDateFechaRecepcion = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jDateFechaEstimativa = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextAreaDiag = new javax.swing.JTextArea();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaDetalle = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));

        jLabel1.setFont(new java.awt.Font("Monospaced", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Nueva Reparacion");

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setText("Tipo de Reparacion");

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel4.setText("Modelo");

        jButtonBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/flecha-izquierda.png"))); // NOI18N
        jButtonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackActionPerformed(evt);
            }
        });

        jButtonCarga.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lifting.png"))); // NOI18N
        jButtonCarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCargaActionPerformed(evt);
            }
        });

        jCBServicio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Servicio" }));
        jCBServicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBServicioActionPerformed(evt);
            }
        });

        jCBTipoRep.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Computadora", "All in one", "Notebook", "Impresora", "Hardware", "Monitor" }));

        jCBSala.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sala/Sector" }));

        jScrollPane2.setViewportView(jTextModelo);

        jLabel5.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jLabel5.setText("La fecha estimativa puede variar. Consulte al int 1829 - Computos");

        jLabel2.setText("Recibido por");

        jCbReceptor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tecnico" }));

        jLabel7.setText("Fecha de recepcion");

        jDateFechaRecepcion.setText("Fecha");

        jLabel9.setText("Fecha estimativa");

        jDateFechaEstimativa.setText("Fecha");

        jTextAreaDiag.setColumns(20);
        jTextAreaDiag.setLineWrap(true);
        jTextAreaDiag.setRows(5);
        jScrollPane4.setViewportView(jTextAreaDiag);

        jTextAreaDetalle.setColumns(20);
        jTextAreaDetalle.setLineWrap(true);
        jTextAreaDetalle.setRows(5);
        jScrollPane1.setViewportView(jTextAreaDetalle);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonBack)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jCBTipoRep, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jCBSala, javax.swing.GroupLayout.Alignment.TRAILING, 0, 174, Short.MAX_VALUE)
                            .addComponent(jButtonCarga, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel9))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jDateFechaEstimativa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jDateFechaRecepcion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jCbReceptor, 0, 180, Short.MAX_VALUE))))
                    .addComponent(jScrollPane4)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                            .addComponent(jCBServicio, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCBServicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCBSala, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jCBTipoRep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jCbReceptor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jDateFechaRecepcion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jDateFechaEstimativa))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonCarga)
                    .addComponent(jButtonBack))
                .addContainerGap(164, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 726));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 571, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCargaActionPerformed

        Reparacion reparacion = new Reparacion();
        Sala sala = new Sala();
        Tecnico receptor = new Tecnico();

        String tipo = jCBTipoRep.getSelectedItem().toString();
        String modelo = jTextModelo.getText();
        String diagnostico = jTextAreaDiag.getText();
        String detalle = jTextAreaDetalle.getText();
        
        for(Sala sal : listaSalas){
            if(sal.getSala().equals(jCBSala.getSelectedItem().toString())){
                sala = controlLogica.buscarSala(sal.getId());
                break;
            }
            else{
               //mostrar mensaje error en la sala
            }
        }
        
        for(Tecnico tec : listaTecnicos){
            if(tec.getNombre().equals(jCbReceptor.getSelectedItem().toString())){
                receptor = controlLogica.buscarTecnico(tec.getId());
                break;
            }
            else{
                //mostrar mensaje error en el tecnico
            }
        }
        
        
        reparacion.setSala(sala);
        reparacion.setTipoDeReparacion(tipo);
        reparacion.setModelo(modelo);
        reparacion.setDiagnostico(diagnostico);
        reparacion.setDetalleTecnico(detalle);
        reparacion.setReceptor(receptor);
        reparacion.setFechaRecepcion(jDateFechaRecepcion.getText());
        reparacion.setFechaEstimativa(jDateFechaEstimativa.getText());
        reparacion.setEstado("A: Recibido");
        
        controlLogica.nuevoReparacion(reparacion);
        
        PrimariaReparaciones reparaciones = new PrimariaReparaciones ();
        reparaciones.setVisible(true);
        reparaciones.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jButtonCargaActionPerformed

    private void jButtonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackActionPerformed
        PrimariaReparaciones reparaciones = new PrimariaReparaciones ();
        reparaciones.setVisible(true);
        reparaciones.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jButtonBackActionPerformed

    private void jCBServicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBServicioActionPerformed
      
        if(jCBServicio.getSelectedIndex() > 0){
            for(Servicio servi : listaServicios){
                if(servi.getNombreServicio().equals(jCBServicio.getSelectedItem().toString())){
                    idServicioSelect = servi.getId();
                    break;
                }
            }
      
            jCBSala.removeAllItems();
            jCBSala.addItem("Seleccione una sala");
            
            for(Sala sala : listaSalas){
                if(sala.getServicio().getId() == idServicioSelect){
                    jCBSala.addItem(sala.getSala());
                }
            }
        }
        
        else if(jCBServicio.getSelectedIndex() == 0){
            jCBSala.removeAllItems();
            jCBSala.addItem("Seleccione un servicio");
            idServicioSelect = -1;
        }
            
        
    }//GEN-LAST:event_jCBServicioActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBack;
    private javax.swing.JButton jButtonCarga;
    private javax.swing.JComboBox<String> jCBSala;
    private javax.swing.JComboBox<String> jCBServicio;
    private javax.swing.JComboBox<String> jCBTipoRep;
    private javax.swing.JComboBox<String> jCbReceptor;
    private javax.swing.JLabel jDateFechaEstimativa;
    private javax.swing.JLabel jDateFechaRecepcion;
    private org.jdatepicker.util.JDatePickerUtil jDatePickerUtil1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextArea jTextAreaDetalle;
    private javax.swing.JTextArea jTextAreaDiag;
    private javax.swing.JTextPane jTextModelo;
    // End of variables declaration//GEN-END:variables
}
