
package IGU.Reparaciones;

import Logica.Controladora;
import Logica.Reparaciones.Reparacion;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.print.attribute.HashPrintRequestAttributeSet;
import javax.print.attribute.PrintRequestAttributeSet;
import javax.print.attribute.standard.Copies;
import javax.print.attribute.standard.PageRanges;

public class ResumenReparacion extends javax.swing.JFrame {

    int idRepa;
    
    public ResumenReparacion(int idRepa) {
        this.idRepa = idRepa;
        
        Controladora controlLogica = new Controladora();
        Reparacion repa = controlLogica.buscarReparacion(idRepa);
        
        initComponents();
        
        if(repa != null){
            Servicio.setText("Servicio: " + repa.getSala().getServicio().getNombreServicio());
            Servicio2.setText("Servicio: " + repa.getSala().getServicio().getNombreServicio());

            Sector.setText("Sector: " + repa.getSala().getSala());
            Sector2.setText("Sector: " + repa.getSala().getSala());

            Modelo.setText(repa.getTipoDeReparacion());
            Modelo2.setText(repa.getTipoDeReparacion());

            Detalle.setText(repa.getModelo());
            Detalle2.setText(repa.getModelo());

            Diagnostico.setText("Diagnostico: " + repa.getDiagnostico());
            Diagnostico2.setText("Diagnostico: " + repa.getDiagnostico());

            DetalleTec.setText("Detalle Tecnico: " + repa.getDetalleTecnico());
            DetalleTec2.setText("Detalle Tecnico: " + repa.getDetalleTecnico());

            FechaRec.setText("Fecha Recepcion " + repa.getFechaRecepcion());
            FechaRec2.setText("Fecha Recepcion " + repa.getFechaRecepcion());

            if(repa.getFechaFinalizacion() != null){
                FechaFin.setText("Fecha Finalizacion " + repa.getFechaFinalizacion());
                FechaFin2.setText("Fecha Finalizacion " + repa.getFechaFinalizacion());
            }
            else{
                FechaFin.setText("Fecha Estimativa " + repa.getFechaEstimativa());
                FechaFin2.setText("Fecha Estimativa " + repa.getFechaEstimativa());
            }
            
            
            if(repa.getReparador()!=null){
               TecReparador.setText("Tecnico Reparador " + repa.getReparador().getNombre());
               TecReparador2.setText("Tecnico Reparador " + repa.getReparador().getNombre());
            }
            else{
                TecReparador.setText("Sin tecnico asignado");
                TecReparador2.setText("Sin tecnico asignado");
            }
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Titulo = new javax.swing.JLabel();
        Servicio = new javax.swing.JLabel();
        Sector = new javax.swing.JLabel();
        Modelo = new javax.swing.JLabel();
        Detalle = new javax.swing.JLabel();
        Diagnostico = new javax.swing.JLabel();
        DetalleTec = new javax.swing.JLabel();
        FechaRec = new javax.swing.JLabel();
        FechaFin = new javax.swing.JLabel();
        TecReparador = new javax.swing.JLabel();
        Titulo2 = new javax.swing.JLabel();
        Servicio2 = new javax.swing.JLabel();
        Sector2 = new javax.swing.JLabel();
        Modelo2 = new javax.swing.JLabel();
        Detalle2 = new javax.swing.JLabel();
        Diagnostico2 = new javax.swing.JLabel();
        DetalleTec2 = new javax.swing.JLabel();
        FechaRec2 = new javax.swing.JLabel();
        FechaFin2 = new javax.swing.JLabel();
        TecReparador2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        Titulo.setFont(new java.awt.Font("DialogInput", 1, 18)); // NOI18N
        Titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Titulo.setText("Hoja de reparacion");

        Servicio.setFont(new java.awt.Font("Lucida Bright", 1, 12)); // NOI18N
        Servicio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Servicio.setText("Servicio");

        Sector.setFont(new java.awt.Font("Lucida Bright", 1, 12)); // NOI18N
        Sector.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Sector.setText("Sector");

        Modelo.setFont(new java.awt.Font("Lucida Bright", 1, 12)); // NOI18N
        Modelo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Modelo.setText("Modelo");

        Detalle.setFont(new java.awt.Font("Lucida Bright", 1, 12)); // NOI18N
        Detalle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Detalle.setText("Detalle");

        Diagnostico.setFont(new java.awt.Font("Lucida Bright", 1, 12)); // NOI18N
        Diagnostico.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Diagnostico.setText("Diagnostico");

        DetalleTec.setFont(new java.awt.Font("Lucida Bright", 1, 12)); // NOI18N
        DetalleTec.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        DetalleTec.setText("Detalle Tecnico");

        FechaRec.setFont(new java.awt.Font("Lucida Bright", 1, 12)); // NOI18N
        FechaRec.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        FechaRec.setText("Fecha recepcion");

        FechaFin.setFont(new java.awt.Font("Lucida Bright", 1, 12)); // NOI18N
        FechaFin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        FechaFin.setText("Fecha finalizacion");

        TecReparador.setFont(new java.awt.Font("Lucida Bright", 1, 12)); // NOI18N
        TecReparador.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TecReparador.setText("Tecnico reparador");

        Titulo2.setFont(new java.awt.Font("DialogInput", 1, 18)); // NOI18N
        Titulo2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Titulo2.setText("Hoja de reparacion");

        Servicio2.setFont(new java.awt.Font("Lucida Bright", 1, 12)); // NOI18N
        Servicio2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Servicio2.setText("Servicio");

        Sector2.setFont(new java.awt.Font("Lucida Bright", 1, 12)); // NOI18N
        Sector2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Sector2.setText("Sector");

        Modelo2.setFont(new java.awt.Font("Lucida Bright", 1, 12)); // NOI18N
        Modelo2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Modelo2.setText("Modelo");

        Detalle2.setFont(new java.awt.Font("Lucida Bright", 1, 12)); // NOI18N
        Detalle2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Detalle2.setText("Detalle");

        Diagnostico2.setFont(new java.awt.Font("Lucida Bright", 1, 12)); // NOI18N
        Diagnostico2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Diagnostico2.setText("Diagnostico");

        DetalleTec2.setFont(new java.awt.Font("Lucida Bright", 1, 12)); // NOI18N
        DetalleTec2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        DetalleTec2.setText("Detalle Tecnico");

        FechaRec2.setFont(new java.awt.Font("Lucida Bright", 1, 12)); // NOI18N
        FechaRec2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        FechaRec2.setText("Fecha recepcion");

        FechaFin2.setFont(new java.awt.Font("Lucida Bright", 1, 12)); // NOI18N
        FechaFin2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        FechaFin2.setText("Fecha finalizacion");

        TecReparador2.setFont(new java.awt.Font("Lucida Bright", 1, 12)); // NOI18N
        TecReparador2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TecReparador2.setText("Tecnico reparador");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Modelo, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addComponent(Detalle, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Titulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Titulo2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Modelo2, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Detalle2, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Servicio, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Sector, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(Diagnostico, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DetalleTec, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(FechaRec, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(FechaFin, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TecReparador, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Servicio2, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Sector2, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(Diagnostico2, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DetalleTec2, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(FechaRec2, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(FechaFin2, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TecReparador2, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Servicio, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Sector, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Modelo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Detalle, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Diagnostico, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(DetalleTec, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(FechaRec)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(FechaFin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TecReparador)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(Titulo2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Servicio2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Sector2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Modelo2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Detalle2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(Diagnostico2, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(DetalleTec2, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(FechaRec2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(FechaFin2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TecReparador2)
                .addGap(15, 15, 15))
        );

        jMenu1.setText("Imprimir");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Atras");
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu2MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
              PrinterJob impresion = PrinterJob.getPrinterJob();
        impresion.setJobName("Datos de retiro");
        impresion.setPrintable(new Printable(){
            @Override
            public int print(Graphics graphics, PageFormat pageFormat, int pageIndex) throws PrinterException {

                Graphics2D g2 = (Graphics2D)graphics;
                g2.translate(pageFormat.getImageableX(),pageFormat.getImageableY());
                g2.scale(1.2,.8);

                jPanel1.paint(g2);
                return Printable.PAGE_EXISTS;
            }

        });

        PrintRequestAttributeSet attr = new HashPrintRequestAttributeSet();
        attr.add(new PageRanges(1,1));
        attr.add(new Copies(1));

        boolean ok = impresion.printDialog(attr);
        if(ok){
            try {
                impresion.print(attr);

            } catch (PrinterException ex) {
                Logger.getLogger(PrimariaReparaciones.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jMenu1MouseClicked

    private void jMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MouseClicked
        PrimariaReparaciones prim = new PrimariaReparaciones();
        prim.setVisible(true);
        prim.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jMenu2MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Detalle;
    private javax.swing.JLabel Detalle2;
    private javax.swing.JLabel DetalleTec;
    private javax.swing.JLabel DetalleTec2;
    private javax.swing.JLabel Diagnostico;
    private javax.swing.JLabel Diagnostico2;
    private javax.swing.JLabel FechaFin;
    private javax.swing.JLabel FechaFin2;
    private javax.swing.JLabel FechaRec;
    private javax.swing.JLabel FechaRec2;
    private javax.swing.JLabel Modelo;
    private javax.swing.JLabel Modelo2;
    private javax.swing.JLabel Sector;
    private javax.swing.JLabel Sector2;
    private javax.swing.JLabel Servicio;
    private javax.swing.JLabel Servicio2;
    private javax.swing.JLabel TecReparador;
    private javax.swing.JLabel TecReparador2;
    private javax.swing.JLabel Titulo;
    private javax.swing.JLabel Titulo2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
